### ISSUE TITLE
Support for survival functions

### ISSUE THREAD

**Issue by ipa** [bambinos/formulae#79]
This is related to: bambinos/bambi#541

To fit a survival function with censored data a response consisting of two components is required. One component depicting the time-to-event and one component depicting the censorship/event status.

Proposing similar to the Surv function in R (https://www.rdocumentation.org/packages/survival/versions/3.3-1/topics/Surv).

```
Surv(time, event)
event: 0 no event / right censored, 1 event
```

Propose to implement this as transformation. The `eval()` method would then simply return a 2xn matrix with time in the first column and event status in the second.

**Comment by tomicapretto** [comment]
I'm closing this since https://github.com/bambinos/bambi/pull/581 as well. Thanks again!
